const photoData=[{src:'assets/photo1.jpg',caption:'I miss this smile❤️'},{src:'assets/photo2.jpg',caption:'I miss seeing you happy.'},{src:'assets/photo3.jpg',caption:'I miss your presence.'},{src:'assets/photo4.jpg',caption:'I miss your random little things. 😭'},{src:'assets/photo5.jpg',caption:'I miss your natkhat rashile nitamb🫦'},{src:'assets/photo6.jpg',caption:'I miss your moans'},{src:'assets/photo7.jpg',caption:'Okay…maybe I miss you a little too much.'},{src:'assets/photo8.jpg',caption:'Actually…definitely too much 🥺'},{src:'assets/photo9.jpg',caption:'Okay, I think you get it now.'}];
const letterTextRaw=`Mikkuuuu I'm missing you so much.....Bahut zayda yaad aa li🥺🥺\n\nAnd today you are going to be busy the whole day....aur tu faltu ka yeh mast soch kr ki aisa ho rha toh teri kya glti and all😭😭\n\nI love you so so much baccha❤️\n\nYou are just mine💋💋💋`;
let currentPhotoIndex=0,musicStarted=false,isLetterOpened=false;const song=document.getElementById('romanticSong'),pill=document.getElementById('musicPill');
function startMusic(){if(musicStarted)return;song.play().then(()=>{musicStarted=true;pill.classList.add('playing');pill.querySelector('.music-text').textContent='Playing for you ❤️';setTimeout(()=>pill.style.opacity=0,3500)}).catch(()=>{})}window.addEventListener('touchstart',startMusic,{passive:true});window.addEventListener('click',startMusic,{passive:true});
function go(id){const a=document.querySelector('.screen.active'),b=document.getElementById(id);if(!a||a===b)return;a.classList.remove('active');setTimeout(()=>{b.classList.add('active');if(id==='screen2')meter();if(id==='screen5')final()},280)}
function meter(){const bar=document.getElementById('meterBar'),pct=document.getElementById('meterPercent'),r=document.getElementById('meterRemark');bar.style.width='0';pct.textContent='0%';r.classList.remove('reveal');let n=0;setTimeout(()=>{bar.style.width='100%';const t=setInterval(()=>{n+=2;pct.textContent=n+'%';if(n>=100){clearInterval(t);setTimeout(()=>r.classList.add('reveal'),300)}},40)},350)}
function initPhotos(){const dots=document.getElementById('deckDots');photoData.forEach((_,i)=>{const d=document.createElement('div');d.className='dot '+(i===0?'active':'');dots.appendChild(d)});showPhoto(0);document.getElementById('btnNextPhoto').onclick=advance}function showPhoto(i){const c=document.getElementById('polaroidCard'),img=document.getElementById('polaroidImg'),cap=document.getElementById('polaroidCaption');c.classList.add('flip-anim');setTimeout(()=>{img.src=photoData[i].src;cap.textContent=photoData[i].caption;document.querySelectorAll('.dot').forEach((d,j)=>d.classList.toggle('active',j===i));c.style.transform=`rotate(${[-2.5,1.8,-1.2,2.2,-1.9,1.5,-2.1,2.4,-1][i]}deg)`;c.classList.remove('flip-anim')},250)}function advance(){if(currentPhotoIndex<8){currentPhotoIndex++;showPhoto(currentPhotoIndex)}if(currentPhotoIndex===8){document.getElementById('btnNextPhoto').classList.add('hidden');setTimeout(()=>document.getElementById('photoConclusion').classList.remove('hidden'),600)}}
function initEnvelope(){document.getElementById('envelopeWrapper').onclick=()=>{if(isLetterOpened)return;isLetterOpened=true;document.getElementById('envelope').classList.add('open');document.getElementById('tapToOpenHint').style.display='none';setTimeout(()=>{let i=0,t=document.getElementById('letterText'),timer=setInterval(()=>{t.innerHTML=letterTextRaw.slice(0,i).replace(/\n/g,'<br>');i++;if(i>letterTextRaw.length){clearInterval(timer);setTimeout(()=>document.getElementById('letterPostscript').classList.remove('hidden'),500)}},18)},700)}}
function final(){['step-1','step-2','step-3','step-4','step-5'].forEach((s,i)=>setTimeout(()=>document.querySelector('.'+s).classList.add('revealed'),500+i*1000))}
function particles(){const c=document.getElementById('particleCanvas'),x=c.getContext('2d');let w=c.width=innerWidth,h=c.height=innerHeight;addEventListener('resize',()=>{w=c.width=innerWidth;h=c.height=innerHeight});const p=Array.from({length:innerWidth<600?28:45},()=>({x:Math.random()*w,y:Math.random()*h,s:Math.random()*8+6,v:Math.random()*.9+.5,o:Math.random()*.5+.25}));function draw(){x.clearRect(0,0,w,h);p.forEach(a=>{a.y-=a.v;if(a.y<-30){a.y=h+20;a.x=Math.random()*w}x.globalAlpha=a.o;x.fillStyle='#ff5376';x.font=a.s+'px serif';x.fillText('♥',a.x,a.y)});requestAnimationFrame(draw)}draw()}
addEventListener('DOMContentLoaded',()=>{particles();initPhotos();initEnvelope();document.getElementById('btnWhy').onclick=()=>go('screen2');document.getElementById('btnNext').onclick=()=>go('screen3');document.getElementById('btnToOneMoreThing').onclick=()=>go('screen4');document.getElementById('btnOneMoreThing').onclick=()=>go('screen5');document.getElementById('btnTalkToMe').onclick=e=>e.currentTarget.textContent='Calling Mikku... 🥺📞❤️'});
